# This is a config for E2B sandbox template.
# You can use template ID (v6ao63rhvjmgpm4vtpg9) or template name (nextjs-nik-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("nextjs-nik-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("nextjs-nik-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nextjs-nik-2')

team_id = "115d3eea-fdad-4887-bcdd-628d3981d68d"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nextjs-nik-2"
template_id = "v6ao63rhvjmgpm4vtpg9"
